#spring.application.name=spring-app
#server.port=9000
spring:
  application:
    name: spring-app
server:
  port: 9000
management:
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ 'env','health','info' ]
