#spring.application.name=spring-app
#server.port=9000
#https://boottechnologies-ci.medium.com/lab2-spring-boot-k8s-kubernetes-health-probes-with-spring-boot-07f06a28433d
spring:
  application:
    name: spring-app
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_LOGIN}:${MONGODB_PWD}@${MONGODB_URL}/${MONGODB_DATABASE}
server:
  port: 9000
management:
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ 'env','health','info' ]

application:
  env:
    db-host: ${host:N/A}
    db-name: ${database:N/A}
    debug: ${debug_mode:0}
